"""Project-wide constants."""

from pathlib import Path

APP_NAME = "securecomm"
VERSION = "0.1.0"

DEFAULT_KEY_ROOT = Path("keys")
DEFAULT_OUTPUT_ROOT = Path("output")

TEXT_ENVELOPE_EXT = ".smsg"
FILE_ENVELOPE_EXT = ".sfile"
SIGNATURE_EXT = ".ssig"
VAULT_EXT = ".svault"

SCHEMA_VERSION = "1"

AES_KEY_SIZE = 32
AES_NONCE_SIZE = 12
X25519_PUBLIC_SIZE = 32
ED25519_PUBLIC_SIZE = 32

MAX_TEXT_BYTES = 1_000_000
DEFAULT_FILE_CHUNK_SIZE = 64 * 1024
MAX_FILE_CHUNK_SIZE = 4 * 1024 * 1024

DEFAULT_ARGON2_TIME_COST = 3
DEFAULT_ARGON2_MEMORY_COST = 128 * 1024
DEFAULT_ARGON2_PARALLELISM = 4
DEFAULT_ARGON2_SALT_BYTES = 16
DEFAULT_ARGON2_HASH_BYTES = 32

DEFAULT_PBKDF2_ITERATIONS = 600_000
DEFAULT_PBKDF2_SALT_BYTES = 16

ENVELOPE_TYPE_TEXT = "text"
ENVELOPE_TYPE_FILE = "file"
ENVELOPE_TYPE_VAULT = "vault"
ENVELOPE_TYPE_SIGNATURE = "signature"

ALG_HYBRID = "X25519+HKDF-SHA256+AES-256-GCM"
ALG_PASSWORD = "ARGON2ID/PBKDF2+AES-256-GCM"
ALG_SIGNATURE = "Ed25519"

HEADER_ENCODING = "utf-8"

INTERACTIVE_PROMPT = "securecomm> "